apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-aapp
  labels:
    name: v-app
    app: v-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: v-app
      app: v-app
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: v-app
      labels:
        name: v-app
        app: v-app

    spec:
      containers:
      - name: v-app
        image: tomcat
        ports:
        - containerPort: 8080
